/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "onConnect": "onConnect",
  "onDisconnect": "onDisconnect",
  "authenticate": "authenticate",
  "logout": "logout",
  "subscribe": "subscribe",
  "unsubscribe": "unsubscribe",
  "emitMessage": "emitMessage",
  "onMessage": "onMessage",
  "progressiveEnhancementExample": "progressiveEnhancementExample",
  "welcomeToPikku": "welcomeToPikku",
  "helloWorld": "helloWorld",
  "rpcTest": "rpcTest",
  "rpcCaller": "rpcCaller",
  "myScheduledTask": "myScheduledTask"
})