/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
import metaData from './pikku-rpc-wirings-meta.internal.gen.json' with { type: 'json' }
pikkuState('rpc', 'meta', metaData as Record<string, string>)