/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "onConnect": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L9C3",
    "exposed": false
  },
  "onDisconnect": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L18C3",
    "exposed": false
  },
  "authenticate": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L28C3",
    "exposed": false
  },
  "subscribe": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L37C3",
    "exposed": false
  },
  "unsubscribe": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L43C3",
    "exposed": false
  },
  "emitMessage": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L51C3",
    "exposed": false
  },
  "onMessage": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L60C3",
    "exposed": false
  },
  "progressiveEnhancementExample": {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "exposed": false
  },
  "timeSinceOpened": {
    "pikkuFuncName": "pikkuFn_src_http_sse_functions_ts_L6C3",
    "exposed": false
  },
  "welcomeToPikku": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L3C58",
    "exposed": false
  },
  "helloWorld": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L7C54",
    "exposed": false
  },
  "rpcTest": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L4C3",
    "exposed": false
  },
  "rpcCaller": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L16C3",
    "exposed": false
  },
  "myScheduledTask": {
    "pikkuFuncName": "pikkuFn_src_scheduled_task_functions_ts_L4C3",
    "exposed": false
  }
})