/**
 * This file was generated by the @pikku/cli
 */
import './pikku-rpc-wirings-meta.gen.js'
import '../function/pikku-functions-meta.gen.js'
import '../function/pikku-functions.gen.js'
import '../schemas/register.gen.js'