/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * MCP-specific type definitions for tree-shaking optimization
 */

import {
  CoreMCPResource,
  CoreMCPTool,
  CoreMCPPrompt,
  wireMCPResource as wireMCPResourceCore,
  wireMCPTool as wireMCPToolCore,
  wireMCPPrompt as wireMCPPromptCore,
  MCPResourceResponse,
  MCPToolResponse,
  MCPPromptResponse,
  AssertMCPResourceURIParams
} from '@pikku/core/mcp'

import type { PikkuFunctionConfig, PikkuFunctionSessionless } from '../function/pikku-function-types.gen.js'

/**
 * Type definition for MCP resources that provide data to AI models.
 *
 * @template In - Input type for the resource request
 * @template URI - URI template string type for compile-time parameter validation
 */
type MCPResourceWiring<In, URI extends string> = CoreMCPResource<PikkuFunctionConfig<In, MCPResourceResponse, 'rpc' | 'session' | 'mcp'>> & { uri: URI }

/**
 * Type definition for MCP tools that AI models can invoke.
 *
 * @template In - Input type for the tool invocation
 */
type MCPToolWiring<In> = CoreMCPTool<PikkuFunctionConfig<In, MCPToolResponse, 'rpc' | 'session' | 'mcp'>>

/**
 * Type definition for MCP prompts that provide templates to AI models.
 *
 * @template In - Input type for the prompt parameters
 */
type MCPPromptWiring<In> = CoreMCPPrompt<PikkuFunctionConfig<In, MCPPromptResponse, 'rpc' | 'session' | 'mcp'>>

/**
 * Registers an MCP resource with the Pikku framework.
 * Resources provide data that AI models can access.
 *
 * @template In - Input type for the resource request
 * @template URI - URI template string for compile-time parameter validation
 * @param mcpResource - MCP resource definition with data provider function
 */
export const wireMCPResource = <In, URI extends string>(
  mcpResource: MCPResourceWiring<In, URI> & AssertMCPResourceURIParams<In, URI>
) => {
  wireMCPResourceCore(mcpResource as any)
}

/**
 * Registers an MCP tool with the Pikku framework.
 * Tools are functions that AI models can invoke.
 *
 * @template In - Input type for the tool invocation
 * @param mcpTool - MCP tool definition with action function
 */
export const wireMCPTool = <In>(
  mcpTool: MCPToolWiring<In>
) => {
  wireMCPToolCore(mcpTool as any)
}

/**
 * Registers an MCP prompt with the Pikku framework.
 * Prompts provide templates that AI models can use.
 *
 * @template In - Input type for the prompt parameters
 * @param mcpPrompt - MCP prompt definition with template function
 */
export const wireMCPPrompt = <In>(
  mcpPrompt: MCPPromptWiring<In>
) => {
  wireMCPPromptCore(mcpPrompt as any)
}

/**
 * Creates a function for handling MCP prompt requests.
 * These functions generate prompt templates for AI models.
 *
 * @template In - Input type for the prompt parameters
 * @param func - Function definition, either direct function or configuration object
 * @returns The unwrapped function for internal use
 */
export const pikkuMCPPromptFunc = <In>(
  func:
    | PikkuFunctionSessionless<In, MCPPromptResponse, 'mcp'>
    | {
        func: PikkuFunctionSessionless<In, MCPPromptResponse, 'mcp'>
        name?: string
      }
): PikkuFunctionConfig<In, MCPPromptResponse, 'mcp'> => {
  return typeof func === 'function' ? { func } : func
}

/**
 * Creates a function for handling MCP tool invocations.
 * These functions perform actions that AI models can request.
 *
 * @template In - Input type for the tool invocation
 * @param func - Function definition, either direct function or configuration object
 * @returns The unwrapped function for internal use
 */
export const pikkuMCPToolFunc = <In>(
  func:
    | PikkuFunctionSessionless<In, MCPToolResponse, 'mcp'>
    | {
      func: PikkuFunctionSessionless<In, MCPToolResponse, 'mcp'>
      name?: string
    }
): PikkuFunctionConfig<In, MCPToolResponse, 'mcp'> => {
  return typeof func === 'function' ? { func } : func
}

/**
 * Creates a function for handling MCP resource requests.
 * These functions provide data that AI models can access.
 *
 * @template In - Input type for the resource request
 * @param func - Function definition, either direct function or configuration object
 * @returns The unwrapped function for internal use
 */
export const pikkuMCPResourceFunc = <In>(
  func:
    | PikkuFunctionSessionless<In, MCPResourceResponse, 'mcp'>
    | {
      func: PikkuFunctionSessionless<In, MCPResourceResponse, 'mcp'>
      name?: string
    }
): PikkuFunctionConfig<In, MCPResourceResponse, 'mcp'> => {
  return typeof func === 'function' ? { func } : func
}
