/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
import type { MCPResourceMeta, MCPToolMeta, MCPPromptMeta } from '@pikku/core/mcp'
import metaData from './pikku-mcp-wirings-meta.gen.json' with { type: 'json' }
pikkuState('mcp', 'resourcesMeta', metaData.resourcesMeta as MCPResourceMeta)
pikkuState('mcp', 'toolsMeta', metaData.toolsMeta as MCPToolMeta)
pikkuState('mcp', 'promptsMeta', metaData.promptsMeta as MCPPromptMeta)