/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { pikkuState } from '@pikku/core'
import type { SerializedWorkflowGraphs } from '@pikku/inspector/workflow-graph'

const workflowsMeta: SerializedWorkflowGraphs = {}

pikkuState(null, 'workflows', 'meta', workflowsMeta)