/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
import { WorkflowsMeta } from '@pikku/core/workflow'
import metaData from './pikku-workflow-wirings-meta.gen.json' with { type: 'json' }

pikkuState('workflows', 'meta', metaData as WorkflowsMeta)
