/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for TypeScript to be aware of workflows and their input/output types
 */



// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type OnConnectInput = "hello!"
export type AuthenticateInput = { token: string; userId: string; }
export type AuthenticateOutput = { authResult: boolean; }
export type SubscribeInput = { name: string; }
export type UnsubscribeInput = { name: string; }
export type UnsubscribeOutput = "valid"
export type EmitMessageInput = { name: string; }
export type EmitMessageOutput = { timestamp: string; from: string; } | { message: string; }
export type OnMessageInput = "hello"
export type OnMessageOutput = "hey"
export type ProgressiveEnhancementExampleOutput = { state: "initial" | "pending" | "done"; }
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { rpcName: string; data?: any; }
export type PikkuFn_rpc_wiring_ts_L30C9Input = { rpcName: string; }

interface WorkflowHandler<I, O> {
    input: I;
    output: O;
}

export type WorkflowMap = {
};


/**
 * Type-safe workflow client API
 */
export type WorkflowClient<Name extends keyof WorkflowMap> = {
  /**
   * Start a new workflow run
   */
  start: (input: WorkflowMap[Name]['input']) => Promise<{ runId: string }>;

  /**
   * Get a workflow run by ID
   */
  getRun: <output extends keyof WorkflowMap[Name]>(runId: string) => Promise<WorkflowMap[Name][output]>;

  /**
   * Cancel a running workflow
   */
  cancelRun: (runId: string) => Promise<boolean>;
}

/**
 * Map of all registered workflows with type-safe client APIs
 */
export type TypedWorkflowClients = {
  [Name in keyof WorkflowMap]: WorkflowClient<Name>;
}
  