/**
 * This file was generated by the @pikku/cli
 */
import './pikku-channels-meta.gen.js'
import '../function/pikku-functions-meta.min.gen.js'
import '../function/pikku-functions.gen.js'
import '../schemas/register.gen.js'
import './pikku-channels.gen.js'