/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('channel', 'meta', {
  "events": {
    "name": "events",
    "route": "/",
    "input": null,
    "connect": null,
    "disconnect": null,
    "message": null,
    "messageWirings": {
      "action": {
        "auth": {
          "pikkuFuncName": "authenticate"
        },
        "subscribe": {
          "pikkuFuncName": "subscribe"
        },
        "unsubscribe": {
          "pikkuFuncName": "unsubscribe"
        },
        "emit": {
          "pikkuFuncName": "emitMessage"
        }
      }
    },
    "tags": [
      "events"
    ]
  },
  "progressive-enhancement": {
    "name": "progressive-enhancement",
    "route": "/status/websocket",
    "input": null,
    "connect": null,
    "disconnect": null,
    "message": null,
    "messageWirings": {
      "action": {
        "status": {
          "pikkuFuncName": "progressiveEnhancementExample"
        }
      }
    }
  }
})