/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */



export type LoginInput = unknown
export type LoginOutput = unknown
export type GetMeInput = unknown
export type GetMeOutput = unknown
export type LogoutInput = unknown
export type LogoutOutput = unknown
export type OnConnectInput = { connected: true; }
export type SubscribeInput = unknown
export type SubscribeOutput = unknown
export type UnsubscribeInput = unknown
export type UnsubscribeOutput = unknown
export type ListTodosInput = unknown
export type ListTodosOutput = unknown
export type GetTodoInput = unknown
export type GetTodoOutput = unknown
export type CreateTodoInput = unknown
export type CreateTodoOutput = unknown
export type UpdateTodoInput = unknown
export type UpdateTodoOutput = unknown
export type DeleteTodoInput = unknown
export type DeleteTodoOutput = unknown
export type CompleteTodoInput = unknown
export type CompleteTodoOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L32C9Input = { rpcName: string; }

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
  readonly 'todos-live': {
    readonly routes: {
      readonly action: {
        readonly auth: ChannelHandler<LoginInput, LoginOutput>,
        readonly subscribe: ChannelHandler<SubscribeInput, SubscribeOutput>,
        readonly unsubscribe: ChannelHandler<UnsubscribeInput, UnsubscribeOutput>,
        readonly list: ChannelHandler<ListTodosInput, ListTodosOutput>,
        readonly create: ChannelHandler<CreateTodoInput, CreateTodoOutput>,
        readonly complete: ChannelHandler<CompleteTodoInput, CompleteTodoOutput>,
      },
    },
    readonly defaultMessage: never,
  },
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
