/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type OnConnectInput = "hello!"
export type AuthenticateInput = { token: string; userId: string; }
export type AuthenticateOutput = { authResult: boolean; }
export type SubscribeInput = { name: string; }
export type UnsubscribeInput = { name: string; }
export type UnsubscribeOutput = "valid"
export type EmitMessageInput = { name: string; }
export type EmitMessageOutput = { timestamp: string; from: string; } | { message: string; }
export type OnMessageInput = "hello"
export type OnMessageOutput = "hey"
export type ProgressiveEnhancementExampleOutput = { state: "initial" | "pending" | "done"; }
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { rpcName: string; data?: any; }
export type PikkuFn_rpc_wiring_ts_L30C9Input = { rpcName: string; }

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
  readonly 'events': {
    readonly routes: {
      readonly action: {
        readonly auth: ChannelHandler<AuthenticateInput, AuthenticateOutput>,
        readonly logout: ChannelHandler<void, never>,
        readonly subscribe: ChannelHandler<SubscribeInput, never>,
        readonly unsubscribe: ChannelHandler<UnsubscribeInput, UnsubscribeOutput>,
        readonly emit: ChannelHandler<EmitMessageInput, EmitMessageOutput>,
      },
    },
    readonly defaultMessage: ChannelHandler<OnMessageInput, OnMessageOutput>,
  },
  readonly 'progressive-enhancement': {
    readonly routes: {
      readonly action: {
        readonly status: ChannelHandler<void, ProgressiveEnhancementExampleOutput>,
      },
    },
    readonly defaultMessage: never,
  },
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
