/**
 * This file was generated by @pikku/cli@0.11.1
 */
import type { SingletonServices } from '../types/application-types.d.js'
import type { Services } from '../types/application-types.d.js'

// Singleton services map: true if required, false if available but unused
export const requiredSingletonServices = {
  'config': true,
  'eventHub': true,
  'jwt': false,
  'logger': true,
  'queueService': false,
  'schedulerService': false,
  'schema': true,
  'secrets': false,
  'variables': true,
  'workflowService': false,
} as const

// Session services map: true if required, false if available but unused
export const requiredSessionServices = {
  'workflow': false,
  'workflowStep': false,
} as const

// Type exports
export type RequiredSingletonServices = Pick<SingletonServices, 'config' | 'eventHub' | 'logger' | 'schema' | 'variables'> & Partial<Omit<SingletonServices, 'config' | 'eventHub' | 'logger' | 'schema' | 'variables'>>

export type RequiredSessionServices = Partial<Services>
