/**
 * This file was generated by the @pikku/cli
 */
/**
 * This file was generated by the @pikku/cli
 */

import type { SingletonServices } from '../types/application-types.d.js'
import type { Services } from '../types/application-types.d.js'
import type { PikkuInteraction } from '@pikku/core'

export const singletonServices = {
    'eventHub': true,
    'jwt': true,
    'logger': true,
} as const

// Singleton services (created once at startup)
// Only includes services that are both required and available in SingletonServices
export type RequiredSingletonServices = Pick<SingletonServices, Extract<keyof SingletonServices, 'config' | 'eventHub' | 'jwt' | 'logger' | 'schema' | 'variables'>> & Partial<Omit<SingletonServices, 'config' | 'eventHub' | 'jwt' | 'logger' | 'schema' | 'variables'>>

// Session services (created per request, can access singleton services)
// Omits singleton services and PikkuInteraction (mcp, rpc, http, channel)
export type RequiredSessionServices = Omit<Services, keyof SingletonServices | keyof PikkuInteraction>
