/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('scheduler', 'meta', {
  "myScheduledTask": {
    "pikkuFuncName": "myScheduledTask",
    "name": "myScheduledTask",
    "schedule": "*/1 * * * *",
    "tags": [
      "hello"
    ]
  }
})
export type ScheduledTaskNames = 'myScheduledTask'