/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
import { ScheduledTasksMeta } from '@pikku/core/scheduler'
import metaData from './pikku-schedulers-wirings-meta.gen.json' with { type: 'json' }

pikkuState('scheduler', 'meta', metaData as ScheduledTasksMeta)

export type ScheduledTaskNames = 'myScheduledTask'