/**
 * This file was generated by @pikku/cli@0.11.3
 */
/* Call middleware group factories to register at module evaluation */
import { httpAuthMiddleware } from '../../src/middleware.js'
httpAuthMiddleware()