/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { pikkuState } from '@pikku/core'
import metaData from './pikku-middleware-groups-meta.gen.json' with { type: 'json' }

// HTTP middleware groups metadata
if (metaData.httpGroups && Object.keys(metaData.httpGroups).length > 0) {
  pikkuState(null, 'middleware', 'httpGroupMeta', metaData.httpGroups)
}

// Tag middleware groups metadata
if (metaData.tagGroups && Object.keys(metaData.tagGroups).length > 0) {
  pikkuState(null, 'middleware', 'tagGroupMeta', metaData.tagGroups)
}
