/**
 * This file was generated by the @pikku/cli
 */
/* The files with an wireHTTP function call */
import '../../src/http-progressive-enhancement.wiring.js'
import '../../src/http-sse.wiring.js'
import '../../src/http.wiring.js'
import '../../src/rpc.wiring.js'