/**
 * This file was generated by @pikku/cli@0.11.3
 */
/* The files with an wireHTTP function call */
import '../../src/wirings/auth.wiring.js'
import '../../src/wirings/rpc.wiring.js'
import '../../src/wirings/todos.http.js'