/**
 * This file was generated by @pikku/cli@0.11.2
 */
/* The files with an wireHTTP function call */
import '../../src/http-progressive-enhancement.wiring.js'
import '../../src/http.wiring.js'
import '../../src/rpc.wiring.js'