/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */



export type LoginInput = unknown
export type LoginOutput = unknown
export type GetMeInput = unknown
export type GetMeOutput = unknown
export type LogoutInput = unknown
export type LogoutOutput = unknown
export type OnConnectInput = { connected: true; }
export type SubscribeInput = unknown
export type SubscribeOutput = unknown
export type UnsubscribeInput = unknown
export type UnsubscribeOutput = unknown
export type ListTodosInput = unknown
export type ListTodosOutput = unknown
export type GetTodoInput = unknown
export type GetTodoOutput = unknown
export type CreateTodoInput = unknown
export type CreateTodoOutput = unknown
export type UpdateTodoInput = unknown
export type UpdateTodoOutput = unknown
export type DeleteTodoInput = unknown
export type DeleteTodoOutput = unknown
export type CompleteTodoInput = unknown
export type CompleteTodoOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L32C9Input = { rpcName: string; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  