/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
import { QueueWorkersMeta } from '@pikku/core/queue'
import metaData from './pikku-queue-workers-wirings-meta.gen.json' with { type: 'json' }

pikkuState('queue', 'meta', metaData as QueueWorkersMeta)