/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('queue', 'meta', {
  "pikku-remote-internal-rpc": {
    "pikkuFuncName": "pikkuRemoteInternalRPC",
    "queueName": "pikku-remote-internal-rpc"
  }
})