/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState, FunctionsRuntimeMeta } from '@pikku/core'
import metaData from './pikku-functions-meta.min.gen.json' with { type: 'json' }
pikkuState('function', 'meta', metaData as FunctionsRuntimeMeta)