/**
 * This file was generated by @pikku/cli@0.11.1
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { rpcTest } from '../../src/rpc.functions.js'

addFunction('rpcTest', rpcTest)