/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "pikkuFn_src_channel_functions_ts_L9C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L9C3",
    "name": "onConnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": "OnConnectInput",
    "inputs": [
      "OnConnectInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L18C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L18C3",
    "name": "onDisconnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L28C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L28C3",
    "name": "authenticate",
    "services": {
      "optimized": true,
      "services": [
        "userSession"
      ]
    },
    "schemaName": "AuthenticateInput",
    "inputs": [
      "AuthenticateInput"
    ],
    "outputs": [
      "AuthenticateOutput"
    ]
  },
  "pikkuFn_src_channel_functions_ts_L37C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L37C3",
    "name": "subscribe",
    "services": {
      "optimized": true,
      "services": [
        "eventHub",
        "channel"
      ]
    },
    "schemaName": "SubscribeInput",
    "inputs": [
      "SubscribeInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L43C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L43C3",
    "name": "unsubscribe",
    "services": {
      "optimized": true,
      "services": [
        "channel",
        "eventHub"
      ]
    },
    "schemaName": "UnsubscribeInput",
    "inputs": [
      "UnsubscribeInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L51C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L51C3",
    "name": "emitMessage",
    "services": {
      "optimized": true,
      "services": [
        "userSession",
        "eventHub",
        "channel"
      ]
    },
    "schemaName": "EmitMessageInput",
    "inputs": [
      "EmitMessageInput"
    ],
    "outputs": [
      "EmitMessageOutput"
    ]
  },
  "pikkuFn_src_channel_functions_ts_L60C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L60C3",
    "name": "onMessage",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": "OnMessageInput",
    "inputs": [
      "OnMessageInput"
    ],
    "outputs": [
      "OnMessageOutput"
    ]
  },
  "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3": {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "name": "progressiveEnhancementExample",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "ProgressiveEnhancementExampleOutput"
    ]
  },
  "pikkuFn_src_http_sse_functions_ts_L6C3": {
    "pikkuFuncName": "pikkuFn_src_http_sse_functions_ts_L6C3",
    "name": "timeSinceOpened",
    "services": {
      "optimized": true,
      "services": [
        "channel"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "TimeSinceOpenedOutput"
    ]
  },
  "pikkuFn_src_http_functions_ts_L3C58": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L3C58",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "string"
    ]
  },
  "pikkuFn_src_http_functions_ts_L7C54": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L7C54",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "string"
    ]
  },
  "pikkuFn_src_rpc_functions_ts_L4C3": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L4C3",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "schemaName": "RpcTestInput",
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_rpc_functions_ts_L16C3": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L16C3",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "schemaName": "RpcCallerInput",
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_scheduled_task_functions_ts_L4C3": {
    "pikkuFuncName": "pikkuFn_src_scheduled_task_functions_ts_L4C3",
    "name": "myScheduledTask",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": []
  }
})