/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "onConnect": {
    "pikkuFuncName": "onConnect",
    "name": "onConnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": "OnConnectInput",
    "outputSchemaName": null,
    "inputs": [
      "OnConnectInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  },
  "onDisconnect": {
    "pikkuFuncName": "onDisconnect",
    "name": "onDisconnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  },
  "authenticate": {
    "pikkuFuncName": "authenticate",
    "name": "authenticate",
    "services": {
      "optimized": true,
      "services": [
        "userSession"
      ]
    },
    "inputSchemaName": "AuthenticateInput",
    "outputSchemaName": "AuthenticateOutput",
    "inputs": [
      "AuthenticateInput"
    ],
    "outputs": [
      "AuthenticateOutput"
    ],
    "isDirectFunction": true
  },
  "logout": {
    "pikkuFuncName": "logout",
    "name": "logout",
    "services": {
      "optimized": true,
      "services": [
        "userSession"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": false
  },
  "subscribe": {
    "pikkuFuncName": "subscribe",
    "name": "subscribe",
    "services": {
      "optimized": true,
      "services": [
        "eventHub",
        "channel"
      ]
    },
    "inputSchemaName": "SubscribeInput",
    "outputSchemaName": null,
    "inputs": [
      "SubscribeInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  },
  "unsubscribe": {
    "pikkuFuncName": "unsubscribe",
    "name": "unsubscribe",
    "services": {
      "optimized": true,
      "services": [
        "channel",
        "eventHub"
      ]
    },
    "inputSchemaName": "UnsubscribeInput",
    "outputSchemaName": "UnsubscribeOutput",
    "inputs": [
      "UnsubscribeInput"
    ],
    "outputs": [
      "UnsubscribeOutput"
    ],
    "isDirectFunction": true
  },
  "emitMessage": {
    "pikkuFuncName": "emitMessage",
    "name": "emitMessage",
    "services": {
      "optimized": true,
      "services": [
        "userSession",
        "eventHub",
        "channel"
      ]
    },
    "inputSchemaName": "EmitMessageInput",
    "outputSchemaName": "EmitMessageOutput",
    "inputs": [
      "EmitMessageInput"
    ],
    "outputs": [
      "EmitMessageOutput"
    ],
    "isDirectFunction": true
  },
  "onMessage": {
    "pikkuFuncName": "onMessage",
    "name": "onMessage",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": "OnMessageInput",
    "outputSchemaName": "OnMessageOutput",
    "inputs": [
      "OnMessageInput"
    ],
    "outputs": [
      "OnMessageOutput"
    ],
    "isDirectFunction": true
  },
  "progressiveEnhancementExample": {
    "pikkuFuncName": "progressiveEnhancementExample",
    "name": "progressiveEnhancementExample",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "ProgressiveEnhancementExampleOutput",
    "inputs": [],
    "outputs": [
      "ProgressiveEnhancementExampleOutput"
    ],
    "isDirectFunction": true
  },
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": [],
    "expose": true,
    "isDirectFunction": false
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": [],
    "isDirectFunction": false
  },
  "pikkuFn_rpc_wiring_ts_L35C9": {
    "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
    "name": "pikkuFn_rpc_wiring_ts_L35C9",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  },
  "myScheduledTask": {
    "pikkuFuncName": "myScheduledTask",
    "name": "myScheduledTask",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  }
})