/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "onConnect": {
    "pikkuFuncName": "onConnect",
    "inputSchemaName": "OnConnectInput",
    "outputSchemaName": null
  },
  "onDisconnect": {
    "pikkuFuncName": "onDisconnect",
    "inputSchemaName": null,
    "outputSchemaName": null
  },
  "authenticate": {
    "pikkuFuncName": "authenticate",
    "inputSchemaName": "AuthenticateInput",
    "outputSchemaName": "AuthenticateOutput"
  },
  "subscribe": {
    "pikkuFuncName": "subscribe",
    "inputSchemaName": "SubscribeInput",
    "outputSchemaName": null
  },
  "unsubscribe": {
    "pikkuFuncName": "unsubscribe",
    "inputSchemaName": "UnsubscribeInput",
    "outputSchemaName": null
  },
  "emitMessage": {
    "pikkuFuncName": "emitMessage",
    "inputSchemaName": "EmitMessageInput",
    "outputSchemaName": "EmitMessageOutput"
  },
  "onMessage": {
    "pikkuFuncName": "onMessage",
    "inputSchemaName": "OnMessageInput",
    "outputSchemaName": "OnMessageOutput"
  },
  "progressiveEnhancementExample": {
    "pikkuFuncName": "progressiveEnhancementExample",
    "inputSchemaName": null,
    "outputSchemaName": "ProgressiveEnhancementExampleOutput"
  },
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "expose": true
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null
  },
  "myScheduledTask": {
    "pikkuFuncName": "myScheduledTask",
    "inputSchemaName": null,
    "outputSchemaName": null
  }
})