/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { addSchema } from '@pikku/core/schema'

import * as OnConnectInput from './schemas/OnConnectInput.schema.json' with { type: 'json' }
addSchema('OnConnectInput', OnConnectInput)


import * as AuthenticateInput from './schemas/AuthenticateInput.schema.json' with { type: 'json' }
addSchema('AuthenticateInput', AuthenticateInput)


import * as AuthenticateOutput from './schemas/AuthenticateOutput.schema.json' with { type: 'json' }
addSchema('AuthenticateOutput', AuthenticateOutput)


import * as SubscribeInput from './schemas/SubscribeInput.schema.json' with { type: 'json' }
addSchema('SubscribeInput', SubscribeInput)


import * as UnsubscribeInput from './schemas/UnsubscribeInput.schema.json' with { type: 'json' }
addSchema('UnsubscribeInput', UnsubscribeInput)


import * as UnsubscribeOutput from './schemas/UnsubscribeOutput.schema.json' with { type: 'json' }
addSchema('UnsubscribeOutput', UnsubscribeOutput)


import * as EmitMessageInput from './schemas/EmitMessageInput.schema.json' with { type: 'json' }
addSchema('EmitMessageInput', EmitMessageInput)


import * as EmitMessageOutput from './schemas/EmitMessageOutput.schema.json' with { type: 'json' }
addSchema('EmitMessageOutput', EmitMessageOutput)


import * as OnMessageInput from './schemas/OnMessageInput.schema.json' with { type: 'json' }
addSchema('OnMessageInput', OnMessageInput)


import * as OnMessageOutput from './schemas/OnMessageOutput.schema.json' with { type: 'json' }
addSchema('OnMessageOutput', OnMessageOutput)


import * as ProgressiveEnhancementExampleOutput from './schemas/ProgressiveEnhancementExampleOutput.schema.json' with { type: 'json' }
addSchema('ProgressiveEnhancementExampleOutput', ProgressiveEnhancementExampleOutput)


import * as RpcTestInput from './schemas/RpcTestInput.schema.json' with { type: 'json' }
addSchema('RpcTestInput', RpcTestInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as PikkuFn_rpc_wiring_ts_L30C9Input from './schemas/PikkuFn_rpc_wiring_ts_L30C9Input.schema.json' with { type: 'json' }
addSchema('PikkuFn_rpc_wiring_ts_L30C9Input', PikkuFn_rpc_wiring_ts_L30C9Input)
