/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { addSchema } from '@pikku/core/schema'

import * as LoginInput from './schemas/LoginInput.schema.json' with { type: 'json' }
addSchema('LoginInput', LoginInput)


import * as LoginOutput from './schemas/LoginOutput.schema.json' with { type: 'json' }
addSchema('LoginOutput', LoginOutput)


import * as GetMeInput from './schemas/GetMeInput.schema.json' with { type: 'json' }
addSchema('GetMeInput', GetMeInput)


import * as GetMeOutput from './schemas/GetMeOutput.schema.json' with { type: 'json' }
addSchema('GetMeOutput', GetMeOutput)


import * as LogoutInput from './schemas/LogoutInput.schema.json' with { type: 'json' }
addSchema('LogoutInput', LogoutInput)


import * as LogoutOutput from './schemas/LogoutOutput.schema.json' with { type: 'json' }
addSchema('LogoutOutput', LogoutOutput)


import * as SubscribeInput from './schemas/SubscribeInput.schema.json' with { type: 'json' }
addSchema('SubscribeInput', SubscribeInput)


import * as SubscribeOutput from './schemas/SubscribeOutput.schema.json' with { type: 'json' }
addSchema('SubscribeOutput', SubscribeOutput)


import * as UnsubscribeInput from './schemas/UnsubscribeInput.schema.json' with { type: 'json' }
addSchema('UnsubscribeInput', UnsubscribeInput)


import * as UnsubscribeOutput from './schemas/UnsubscribeOutput.schema.json' with { type: 'json' }
addSchema('UnsubscribeOutput', UnsubscribeOutput)


import * as ListTodosInput from './schemas/ListTodosInput.schema.json' with { type: 'json' }
addSchema('ListTodosInput', ListTodosInput)


import * as ListTodosOutput from './schemas/ListTodosOutput.schema.json' with { type: 'json' }
addSchema('ListTodosOutput', ListTodosOutput)


import * as GetTodoInput from './schemas/GetTodoInput.schema.json' with { type: 'json' }
addSchema('GetTodoInput', GetTodoInput)


import * as GetTodoOutput from './schemas/GetTodoOutput.schema.json' with { type: 'json' }
addSchema('GetTodoOutput', GetTodoOutput)


import * as CreateTodoInput from './schemas/CreateTodoInput.schema.json' with { type: 'json' }
addSchema('CreateTodoInput', CreateTodoInput)


import * as CreateTodoOutput from './schemas/CreateTodoOutput.schema.json' with { type: 'json' }
addSchema('CreateTodoOutput', CreateTodoOutput)


import * as UpdateTodoInput from './schemas/UpdateTodoInput.schema.json' with { type: 'json' }
addSchema('UpdateTodoInput', UpdateTodoInput)


import * as UpdateTodoOutput from './schemas/UpdateTodoOutput.schema.json' with { type: 'json' }
addSchema('UpdateTodoOutput', UpdateTodoOutput)


import * as DeleteTodoInput from './schemas/DeleteTodoInput.schema.json' with { type: 'json' }
addSchema('DeleteTodoInput', DeleteTodoInput)


import * as DeleteTodoOutput from './schemas/DeleteTodoOutput.schema.json' with { type: 'json' }
addSchema('DeleteTodoOutput', DeleteTodoOutput)


import * as CompleteTodoInput from './schemas/CompleteTodoInput.schema.json' with { type: 'json' }
addSchema('CompleteTodoInput', CompleteTodoInput)


import * as CompleteTodoOutput from './schemas/CompleteTodoOutput.schema.json' with { type: 'json' }
addSchema('CompleteTodoOutput', CompleteTodoOutput)
